all:
	g++ -std=c++11 gen_bfs_push_data.cpp -o gen_bfs_push
	g++ -std=c++11 gen_bfs_pull_data.cpp -o gen_bfs_pull
	g++ -std=c++11 gen_ewsd_data.cpp -o gen_ewsd
	g++ -std=c++11 gen_spmm_data.cpp -o gen_spmm
